/* This file is auto generated by ./register_rule.sh. Do not touch it. */

/* Adding the function definitions. */
void *check_id_size(Eventinfo *lf);
void *comp_mswin_targetuser_calleruser_diff(Eventinfo *lf);
void *comp_srcuser_dstuser(Eventinfo *lf);
void *is_simple_http_request(Eventinfo *lf);
void *is_valid_crawler(Eventinfo *lf);

/* Adding the rules list. */
void *(compiled_rules_list[]) = 
{
    check_id_size,
    comp_mswin_targetuser_calleruser_diff,
    comp_srcuser_dstuser,
    is_simple_http_request,
    is_valid_crawler,
    NULL
};

/* Adding the rules list names. */
char *(compiled_rules_name[]) = 
{
    "check_id_size",
    "comp_mswin_targetuser_calleruser_diff",
    "comp_srcuser_dstuser",
    "is_simple_http_request",
    "is_valid_crawler",
    NULL
};

/* EOF */
